### ISSUE TITLE
Mantenimiento - SEO - Definición de etiquetas meta para mejorar posicionamiento de la aplicación web

### ISSUE THREAD

**Issue by jualoppaz** [jualoppaz/pronostigol#263]
El objetivo de esta tarea es definir aquellas etiquetas meta que sirvan para mejorar el posicionamiento de la web en los buscadores.

- [x] Añadir etiquetas "keyword" en las páginas principales de la web.
- [x] Añadir etiquetas relacionadas con opengraph (Facebook).
- [x] Añadir etiquetas relacionadas con Twitter.
